wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 1.6745598158247553e-05
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 1.573559583461113e-06
