wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 1.902677905879729e-05
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 1.494919428850471e-07
