wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 8
learning_rate:
  value: 2.021571099599782e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 1.622177239267359e-07
