wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 7.447057246572986e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 1.916524982939064e-07
