wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.0007640387774331416
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 7.848259834753626e-06
