wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 5.9105888937953504e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 2.1092801540191473e-06
