wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 8
learning_rate:
  value: 0.00011243372018793092
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 3.200428944886697e-06
