wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 0.0009869065545714335
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 7.075796592902632e-07
