wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 4.056472341066004e-05
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 2.0706128490576504e-06
