wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 2.469617174150852e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 1.1027414893427167e-07
