wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 0.0007827160080012804
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 7.559457415206472e-06
