wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.0002441990054053764
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 2.045121513751532e-06
