wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0006330108849744555
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 3.4836935282011835e-06
