wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 5.5802122289184826e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 4.138581137226956e-07
