wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.000789435978597886
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 9.704874430322708e-06
