wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 2.469841256478496e-05
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 1.0213775129679906e-06
