wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0004963631081407036
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 2.848260630525451e-07
