wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 8
learning_rate:
  value: 1.1487049978524088e-05
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 1.7421252885362446e-07
