wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.00042364592390284193
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 2.3244777850464565e-06
