wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.0003271143620200549
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 1.840420906931673e-07
