wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0005554206766123552
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 7.403124557145006e-06
