wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.00033489657394051247
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 3.33524371930293e-07
