wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 0.0007389350975454531
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 8.805858155166627e-06
