wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.00018888982068144788
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 1.0484443851099029e-07
