wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 5.858324463758867e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 1.856504118036292e-06
