wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.00011456742360182242
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 2.811505548169221e-06
