wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 0.0004614076491889534
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 1.2864652564139027e-06
