wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 3.195215507550201e-05
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 4.448436304998395e-07
