wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 15
learning_rate:
  value: 6.319870920042743e-05
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 7.375857502496247e-06
