wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0007401977699602975
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 1.0894030304527123e-06
