wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 0.000252982804159201
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 6.862765243560104e-06
