wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 1.3488690798335406e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 7.787291119153499e-07
