wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 1.1335927322383887e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 7.658209696809138e-07
