wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 1.094820519247916e-05
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 5.118881478886384e-07
