wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0009549271458054594
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 1.1490612655792494e-07
