wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0008997346362531643
p_attention_dropout:
  value: 0.15
p_decoder_dropout:
  value: 0.1
weight_decay:
  value: 5.561085850437423e-07
