wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0006670152278609237
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 3.3955631848504377e-07
