wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1745144281
    t:
      1:
      - 1
      - 3
      - 5
      - 53
      - 55
      4: 3.6.13
      5: 0.12.21
      8:
      - 1
      - 5
