wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 8
learning_rate:
  value: 0.00015032685482097922
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 1.7192093522673266e-06
