wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 8
learning_rate:
  value: 1.652791172255419e-05
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.15
weight_decay:
  value: 3.010634943858799e-07
