wandb_version: 1

batch_size:
  value: 16
early_stopping_patience:
  value: 15
learning_rate:
  value: 1.7390217682849026e-05
p_attention_dropout:
  value: 0.1
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 1.068285072444989e-07
