wandb_version: 1

batch_size:
  value: 32
early_stopping_patience:
  value: 10
learning_rate:
  value: 0.0002580970997506766
p_attention_dropout:
  value: 0.05
p_decoder_dropout:
  value: 0.05
weight_decay:
  value: 1.105550320263636e-07
